# -*- coding: utf-8 -*-
"""Task 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AgHboEkPvUi18Nq3b_yDCSkjtA02ckzG
"""

# Task 2: Create a Personalized Greeting

# Take user inputs
first_name = input("Enter your first name: ")
last_name = input("Enter your last name: ")

# Concatenate full name
full_name = first_name + " " + last_name

# Print personalized greeting
print(f"\nHello, {full_name}, Welcome to the Python program")